version: '3'
services:
  php:
    image: php:8.2-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
      - 443:443
    links:
      - db
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: sgs2
      MYSQL_USER: root
      MYSQL_PASSWORD:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD:
