version: '3'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './public:/usr/share/nginx/html'
    depends_on:
      - php

  php:
    image: 'php:8.2-fpm'
    volumes:
      - './:/usr/share/nginx/html'

  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - './data:/var/lib/mysql'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
