version: '3'
services:
  php:
    image: php:8.2-apache
    container_name: php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sgs:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sgs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=

volumes:
  mysql-data:
